# 11\06\2026

In [1]:
import numpy  as np

In [2]:
lst = [1,2,3,4,5,6]
al = np.array(lst)
lst

[1, 2, 3, 4, 5, 6]

In [4]:
print(al)
al

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [15]:
import numpy  as np
lst = [1,2,3,5,]
al=np.array(lst)


In [17]:
print(al)

[1 2 3 5]


# Numpy Data Types

# Ways to create Numpy Arrays

In [18]:
import  numpy as np
nar1=np.array([1,3,4,5.0])
nar1

array([1., 3., 4., 5.])

## Creating array by specifying own datatype

In [19]:
l=[1,2,3,4,5]
ar=np.array(l,dtype=np.int64)
ar

array([1, 2, 3, 4, 5])

## To check type,dtype and size

In [24]:
l=[1,2,3,4,5]
ar=np.array(l,dtype=np.int64)
ar

array([1, 2, 3, 4, 5])

In [25]:
print(type(ar))

<class 'numpy.ndarray'>


In [26]:
print(ar.itemsize)

8


In [27]:
print(ar.dtype)

int64


# Ways to create numpy Arrays

## 2.Creating ndarray usig fromiter

In [28]:
ad={1:"A",2:"B",3:"C"}
ar2=np.fromiter(ad,dtype=np.int32)
print(ar2)

[1 2 3]


In [30]:
ar2.dtype

dtype('int32')

In [31]:
ar2.itemsize

4

In [50]:
import numpy as np
arr2 = np.arange(1, 6)
print(arr2[0], arr2[3])

1 4


## 3.arrange() function is used to create array from range

In [40]:
import numpy as np
arr1=np.arange(5)
print(arr1)

[0 1 2 3 4]


In [41]:
import numpy as np
arr2=np.arange(1, 7, 2,dtype=np.float32)
print(arr2)

[1. 3. 5.]


In [42]:
import numpy as np
arr3 = np.linspace(2,3,6)
arr3

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [44]:
import numpy as np
arr4 = np.linspace(2.5,5,8)
arr4

array([2.5       , 2.85714286, 3.21428571, 3.57142857, 3.92857143,
       4.28571429, 4.64285714, 5.        ])

# 2D Numpy Arrays

In [48]:
import numpy as np
A=np.array([[10,11,12,13],[21,22,23,24]])
A[1,3]

np.int64(24)

In [49]:
print(A)

[[10 11 12 13]
 [21 22 23 24]]


In [51]:
A

array([[10, 11, 12, 13],
       [21, 22, 23, 24]])

In [52]:
type(A),type(al)

(numpy.ndarray, numpy.ndarray)

In [53]:
al.shape

(4,)

In [56]:
A.shape

(2, 4)

In [57]:
A.itemsize

8

## 2.Creating 2D ndarrays using arrange -

#### in the similar manner as we have created 1D ndarrays with arrange() function,We can also created 2D ndarays with arranges along with reshape().

#### <ndarray>.reshape(<shape tuple>)

In [7]:
import numpy as np
ar1 = np.arange(10)
print(ar1)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
ar3=ar1.reshape
ar3

<function ndarray.reshape>

# 3.ARRAYS CREATION ALTERNATIVE METHODS -

#### a.using empty()
empty() function can be used to create empty array or an unitialized array of specified shape and dtype

## numpy.empty(shape,[dtype=<datatype>,][order='c'or'f']

## Where:datatype:is a data type of python or numpy to set initial vallues shape:is dimension

## Order:'C' means arrangement of data as row wise (C menas C like)
Order:'F' menas arrangement of data as row wise(F menas fortran like)

In [9]:
arr1=np.empty([2,3],dtype=np.int64,order='C')
arr1

array([[25895968444448860, 23925768161198147, 32370111954616435],
       [30681189080825948, 18296268630196329, 27303364806049904]])

## b.Using zeros()-

#### numpy.zeros(Shape,[dtype=<datatupe>,][order='C'or'F'])

In [11]:
ar3=np.zeros([2,3],dtype=np.int64,order='F')
ar3

array([[0, 0, 0],
       [0, 0, 0]])

### c.Using ones()-

**numpy.ones(Shape,[dtype=<datatype>,][order='C'or'F'])**


In [14]:
ar4=np.ones([2,3],dtype=np.float32)
ar4

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

# Array Slicing -

#### it is possible to extract subsets of Nimpy arrays using slices,just like lists.

<Arrayname>[<start>:<stop>:<step>]

#### . When <start><stop> or<step> values are not specified then python will assume thier default values as:
Start=0;Stop=dimension size;Step=1

In [18]:
arr=np.array([2,4,6,8,10,12,14,16,18,20])
arr[3:6]

array([ 8, 10, 12])

In [19]:
arr[:5]

array([ 2,  4,  6,  8, 10])

arr[4:]

In [20]:
arr[:-1]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
arr[:-3]

array([ 2,  4,  6,  8, 10, 12, 14])

In [22]:
arr[2:7:2]

array([ 6, 10, 14])

#### Syntax

# Numpy.hstack(<tuple containing names of 1D arrays to be stacked>)

# Numpy.vstack(<tuple conating names of 1D arrays to be stacked>)

In [23]:
arr[2:7:2]

array([ 6, 10, 14])

In [24]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
a1=np.array(list1)
a1

array([1, 2, 3, 4, 5])

In [25]:
a2=np.array(list2)
a2

array([ 6,  7,  8,  9, 10])

In [28]:
join1 = np.hstack((a1, a2))
print(join1)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
join2=np.vstack((a1,a2))
join2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# COMBININIG EXISTING ARRAYS USING CONCATENATE

In [31]:
a1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a2=np.array([1,2,3,4,5,6]).reshape(2,3)
print(a2)

[[1 2 3]
 [4 5 6]]


In [37]:
a3=np.array([1,2,3,4,5,6]).reshape(3,2)
print(a3)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
a3=np.array([1,2,3]).reshape(3,1)
print(a3)

[[1]
 [2]
 [3]]


In [40]:
j1=np.concatenate((a1,a3),axis=1)
j1

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

# OBTAINING SUBSETS OF ARRAYS-

In [43]:
ary=np.arange(24.0).reshape(4,6)
ary

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [45]:
np.hsplit(ary,2)

[array([[ 0.,  1.,  2.],
        [ 6.,  7.,  8.],
        [12., 13., 14.],
        [18., 19., 20.]]),
 array([[ 3.,  4.,  5.],
        [ 9., 10., 11.],
        [15., 16., 17.],
        [21., 22., 23.]])]

In [46]:
np.vsplit(ary,2)

[array([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])]

In [47]:
ary=np.arange(24.0).reshape(4,6)
ary

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [49]:
np.split(ary,[1,4])

[array([[0., 1., 2., 3., 4., 5.]]),
 array([[ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([], shape=(0, 6), dtype=float64)]

In [52]:
np.split(ary,[2,5],axis=1)

[array([[ 0.,  1.],
        [ 6.,  7.],
        [12., 13.],
        [18., 19.]]),
 array([[ 2.,  3.,  4.],
        [ 8.,  9., 10.],
        [14., 15., 16.],
        [20., 21., 22.]]),
 array([[ 5.],
        [11.],
        [17.],
        [23.]])]

# Extracting condition based Non-Contiguous Subsets

In [53]:
ary

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [54]:
cond=np.mod(ary,5)==0
cond

array([[ True, False, False, False, False,  True],
       [False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False]])

# Arithmatic opretion on 2D arrays-

In [55]:
ary+1.5

array([[ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5],
       [ 7.5,  8.5,  9.5, 10.5, 11.5, 12.5],
       [13.5, 14.5, 15.5, 16.5, 17.5, 18.5],
       [19.5, 20.5, 21.5, 22.5, 23.5, 24.5]])

In [56]:
new=ary+2.1
ary+new

array([[ 2.1,  4.1,  6.1,  8.1, 10.1, 12.1],
       [14.1, 16.1, 18.1, 20.1, 22.1, 24.1],
       [26.1, 28.1, 30.1, 32.1, 34.1, 36.1],
       [38.1, 40.1, 42.1, 44.1, 46.1, 48.1]])

In [57]:
np.multiply(ary,3)

array([[ 0.,  3.,  6.,  9., 12., 15.],
       [18., 21., 24., 27., 30., 33.],
       [36., 39., 42., 45., 48., 51.],
       [54., 57., 60., 63., 66., 69.]])

# Apllication on Numpy Arrays-

In [58]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,0,-1,-3])
check=np.cov(a,b)
check

array([[ 2.5 , -4.25],
       [-4.25,  8.3 ]])